### ISSUE TITLE
please consider return-rw

### ISSUE THREAD

**Issue by gfldex** [alabamenhu/DebugTransput#1]
```
sub b(\c) { return-rw c }

my $c = 1;
b($c)++;
say $c;
```

The above code alloes `postfix:<++>`. Using a simple `return` will strip the container, even if a sigilless argument is used.

**Comment by alabamenhu** [comment]
Oh, didn't think about that.  I'll push an update today to do just that.

**Comment by alabamenhu** [comment]
Implemented in v.0.1.1 !  Thanks so much for pointing this out.
